# scripts/config/train.yaml
seed: 1234
#dataset: "data/maze_preprocessed/mazes_032_moore_c8_ours"
dataset: "data/maze_preprocessed/mixed_064_moore_c16_ours"
#dataset: "data/maze_preprocessed/all_064_moore_c16_ours"
logdir: "model"
Tmax: 0.25
mode: "ours" # Options: neural_astar, ours

encoder:
  input: "msg"
  arch: "MultiHeadGeoUnet"
  backbone: "vgg16_bn" # used by MultiHeadGeoUnet
  #  depth: 2 # 32x32
  depth: 3 # 64x64

params:
  batch_size: 16
  num_epochs: 10
  lr: 1e-4
  num_workers: 4

  # Loss Weights
  path_loss_weight: 1.0 # default
  geo_loss_weight: 1.0
  dist_loss_weight: 1.0
  vec_loss_weight: 0.1

  # Warmup Strategy
  geo_warmup_epochs: 0

hydra:
  job:
    chdir: False
