# scripts/config/train.yaml
seed: 1234
#dataset: "data/maze_preprocessed/mazes_032_moore_c8_ours"
dataset: "data/maze_preprocessed/mixed_064_moore_c16_ours"
#dataset: "data/maze_preprocessed/all_064_moore_c16_ours"
logdir: "model"
Tmax: 0.25
mode: "ours" # Options: neural_astar, ours

encoder:
  input: "msg"
  arch: "MultiHeadGeoUnet"
  backbone: "vgg16_bn"
  #depth: 2 # 32x32
  depth: 3 # 64x64

params:
  batch_size: 32
  num_epochs: 100
  lr: 1e-4
  num_workers: 4

  # Loss Weights
  path_loss_weight: 1.0
  geo_loss_weight: 0.1
  dist_loss_weight: 1.0
  vec_loss_weight: 1.0
  consistency_weight: 0.5

  use_uncertainty_weighting: false
  use_weno_gradient: true

hydra:
  job:
    chdir: False
