name: neural-astar-heat-method
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults

dependencies:
  - python=3.11.9
  - pip=24.3.1
  - pytorch==2.5.1
  - torchvision==0.20.1
  - torchaudio=2.5.1
  - pytorch-cuda=11.8
  - numpy=2.3.0
  - scipy=1.16.2
  - pytorch-lightning=2.5.5
  - tensorboard
  - tensorboardx
  - matplotlib
  - tqdm
  - plyfile
  - jupyterlab
  - hydra-core
  - pyyaml

  - pip:
      - segmentation-models-pytorch
      - pqdict
      - moviepy
      - potpourri3d
      - trimesh
